# Generated by Django 5.2.6 on 2025-10-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_rate',
            field=models.IntegerField(default=0),
        ),
    ]
