# Generated by Django 5.2.6 on 2025-10-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_newsletter_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
